/*
 * This source file was generated by the Gradle 'init' task
 */
package assignments;

import java.util.List;
import java.util.concurrent.TimeUnit;

import org.openqa.selenium.By;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Keys;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedCondition;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.testng.Assert;
import org.testng.annotations.AfterClass;
import org.testng.annotations.BeforeClass;
import org.testng.annotations.Test;

import io.github.bonigarcia.wdm.WebDriverManager;

class AppTest {
    
    WebDriver driver;
    WebDriverWait waiter;

    @BeforeClass
    void start(){
        WebDriverManager.chromedriver().setup();
        driver = new ChromeDriver();
        driver.manage().window().maximize();
        driver.manage().timeouts().implicitlyWait(1, TimeUnit.SECONDS);
        waiter = new WebDriverWait(driver, 5);
    }

    // @Test //Due to poor performance/design of the website, test case has like 40% chance of failing due to not finding product
    void B_1(){
        driver.get("https://web.platform.kwibal.com/");
        WebElement searchBar = waiter.until(ExpectedConditions.visibilityOfElementLocated(By.name("search")));
        searchBar.sendKeys("perfume");
        new Actions(driver).sendKeys(Keys.ENTER).perform();

        waiter.until(ExpectedConditions.visibilityOfElementLocated(By.xpath("//button[contains(@class,\"jsx-4268230244\")]")));
        List<WebElement> items = driver.findElements(By.xpath("//div[contains(@class,\"image\")]"));
        System.out.println("size:"+items.size());
        Assert.assertNotEquals(items.size(),0, "No product found");
    }

    void B2_WaitForButton(By locator){
        waiter.until(ExpectedConditions.elementToBeClickable(locator));
    }

    @Test
    void B3_endToEnd(){
        driver.get("https://crio-qkart-frontend-qa.vercel.app");
        WebElement loginButton = waiter.until(ExpectedConditions.elementToBeClickable(By.xpath("//button[text()=\"Login\"]")));
        loginButton.click();
        WebElement username = waiter.until(ExpectedConditions.visibilityOfElementLocated(By.id("username")));
        username.sendKeys("05072025a");
        WebElement password = driver.findElement(By.id("password"));
        password.sendKeys("05072025a");
        WebElement login2 = driver.findElement(By.className("css-177pwqq"));
        login2.click();

        WebElement addtoCart = waiter.until(ExpectedConditions.elementToBeClickable(By.className("css-54wre3")));
        new Actions(driver).sendKeys(Keys.ESCAPE).perform();
        addtoCart.click();
        WebElement checkoutButton = waiter.until(ExpectedConditions.visibilityOfElementLocated(By.className("css-177pwqq")));
        checkoutButton.click();

        try{
            waiter.until(ExpectedConditions.visibilityOfElementLocated(By.className("css-1ifef37")));
            waiter.until(ExpectedConditions.elementToBeClickable(By.id("add-new-btn"))).click();
            WebElement AddressField = driver.findElement(By.tagName("textarea"));
            AddressField.sendKeys("20 character limit k");
            driver.findElement(By.xpath("//button[text()='Add']")).click();
        }catch(Exception e){}
        
        driver.findElement(By.className("address-item")).click();

        driver.findElement(By.xpath("//button[text()='PLACE ORDER']")).click();

        try{
            waiter.until(ExpectedConditions.not(ExpectedConditions.presenceOfElementLocated(By.xpath("//button[text()='PLACE ORDER']"))));
        }catch(Exception e){}
            System.out.println(driver.getCurrentUrl());
        Assert.assertTrue(driver.getCurrentUrl().contains("thanks"));
    }

    @AfterClass
    void end(){
        driver.quit();
    }
}
